apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.controller.expose.port: "true"
    kompose.init.containers.command: echo Initializing api gateway service
    kompose.init.containers.image: docker.io/library/deployment-api-gateway-service:latest
    kompose.service.healthcheck.readiness.start_period: 30s
    kompose.service.healthcheck.readiness.test: CMD curl -f http://localhost:8009/health
    kompose.service.readinessProbe.httpGet.port: "8009"
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: api-gateway-service
  name: api-gateway-service
spec:
  ports:
    - name: "8009"
      port: 8009
      targetPort: 8009
  selector:
    io.kompose.service: api-gateway-service
