apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.controller.expose.port: "true"
    kompose.init.containers.command: echo Initializing auth service
    kompose.service.healthcheck.readiness.start_period: 30s
    kompose.service.healthcheck.readiness.test: CMD curl -f http://localhost:8010/health
    kompose.service.readinessProbe.httpGet.port: "8010"
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: auth-service
  name: auth-service
spec:
  ports:
    - name: "8010"
      port: 8010
      targetPort: 8010
  selector:
    io.kompose.service: auth-service
