apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.controller.expose.port: "true"
    kompose.init.containers.command: echo Initializing auth postgres database
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: auth-postgres-db
  name: auth-postgres-db
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: auth-postgres-db
