apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.controller.expose.port: "true"
    kompose.init.containers.command: echo Initializing backend service
    kompose.init.containers.image: docker.io/library/backend-service:latest
    kompose.service.readinessProbe.httpGet.port: "5128"
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: backend-service
  name: backend-service
spec:
  ports:
    - name: "5128"
      port: 5128
      targetPort: 5128
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: backend-service
