import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { jwtVerify } from "jose"; // For verifying the JWT
import "./globals.css";

import Navbar from "@/components/Navbar";
import FlowbiteProvider from "@/components/FlowbiteProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//const inter = Inter({ subsets: ['latin'] });

const JWT_SECRET = new TextEncoder().encode(
  process.env.JWT_SECRET || "secret_jwt_key",
);

interface UserPayload {
  userId: string;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user: UserPayload | null = null;
  const cookieStore = await cookies();
  const token = cookieStore.get("auth_token")?.value;

  if (token) {
    try {
      const { payload } = await jwtVerify(token, JWT_SECRET, {
        algorithms: ["HS256"], // Use the algorithm you used to sign your JWTs
      });
      user = payload as unknown as UserPayload;
    } catch (error) {
      console.error("JWT verification failed in layout:", error);
    }
  }
  user = { userId: "some_user_id" };
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FlowbiteProvider />
        <Navbar initialUser={user} />
        {children}
      </body>
    </html>
  );
}
